### ISSUE TITLE
can we have an example of gorok.yaml in config folder?

### ISSUE THREAD

**Issue by MkLHX** [tystuyfzand/gogrok#1]
Hi, 

Thanks for this project! It looks like what i'm looking for.

I try to use it in docker containers. I just need an example of gorok.yaml config file to configure the server instance.

Could you provide it please?

**Comment by tystuyfzand** [comment]
There aren't any required configuration items for the server/client, but you can also use environment variables (which are bound to flags, etc). For docker, this is what I use:

```
version: '3.7'

services:
  gogrok:
    image: tystuyfzand/gogrok:latest
    ports:
    - mode: host
      target: 2222
      published: 2222
    volumes:
    - /docker/gogrok/config:/config
    environment:
    - GOGROK_ARGS=serve
    - GOGROK_DOMAINS=gogrok.ccatss.dev
    - GOGROK_AUTHORIZED_KEY_FILE=/config/authorized_keys
```

A sample gogrok.yaml for the server would be something like:

```yaml
gogrok:
  sshAddress: ":2222"
  httpAddress: ":8080"
  authorizedKeyFile: /config/authorized_keys
  storageDir: /config
  domains:
    - gogrok.ccatss.dev
```

For a client:

```yaml
gogrok:
  storageDir: /var/lib/gogrok
  server: SERVER_IP:2222
  clientKey: /var/lib/gogrok/client.key
  clientKeyPassphrase: OPTIONAL
```

I'll get these added into the repository in a bit - currently I have some uncommitted changes from TLS (TCP, but with hostnames for shared port binding) and basic TCP forwarding that I'm working on.
